build: off

skip_tags: true

branches:
  only:
    - master

environment:
  nodejs_version: "6"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
